android_library(
    name = "sugar",
    srcs = [
        "com/orm/SugarApp.java",
        "com/orm/SugarRecord.java",
        "com/orm/SugarDataSource.java",
        "com/orm/util/MigrationFileParser.java",
        "com/orm/util/ThreadUtil.java",
        "com/orm/util/SugarCursorFactory.java",
        "com/orm/util/QueryBuilder.java",
        "com/orm/util/SugarCursor.java",
        "com/orm/util/SugarConfig.java",
        "com/orm/util/NumberComparator.java",
        "com/orm/util/ContextUtil.java",
        "com/orm/util/ReflectionUtil.java",
        "com/orm/util/KeyWordUtil.java",
        "com/orm/annotation/OneToMany.java",
        "com/orm/annotation/Ignore.java",
        "com/orm/annotation/Table.java",
        "com/orm/annotation/Column.java",
        "com/orm/annotation/MultiUnique.java",
        "com/orm/annotation/NotNull.java",
        "com/orm/annotation/Unique.java",
        "com/orm/SchemaGenerator.java",
        "com/orm/SugarDb.java",
        "com/orm/SugarDbConfiguration.java",
        "com/orm/SugarContext.java",
        "com/orm/query/Select.java",
        "com/orm/query/Condition.java",
        "com/orm/helper/NamingHelper.java",
        "com/orm/helper/SugarTransactionHelper.java",
        "com/orm/helper/MultiDexHelper.java",
        "com/orm/helper/ManifestHelper.java",
        "com/orm/inflater/field/ListFieldInflater.java",
        "com/orm/inflater/field/FieldInflater.java",
        "com/orm/inflater/field/EntityFieldInflater.java",
        "com/orm/inflater/field/DefaultFieldInflater.java",
        "com/orm/inflater/field/RelationEntityFieldInflater.java",
        "com/orm/inflater/EntityInflater.java",
    ],
    manifest = "AndroidManifest.xml",
    custom_package = "com.orm.dsl"
)
